<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="George Michaelides">
<meta name="dcterms.date" content="2026-01-01">

<title>CFA — practical – A Step-by-Step Introduction to Structural Equation Modeling with lavaan in R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../tutorials/08-parcels-second-order.html" rel="next">
<link href="../tutorials/06-cfa-concept.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5dad907783eb94222aa6c9b08b9eb4a6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-bc5b62d811c1c94b7e95d620c4441ad7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-5dad907783eb94222aa6c9b08b9eb4a6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 15,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">A Step-by-Step Introduction to Structural Equation Modeling with lavaan in R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../glossary.html"> 
<span class="menu-text">Glossary</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notation.html"> 
<span class="menu-text">Notation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cheatsheet.html"> 
<span class="menu-text">Cheat sheet</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/michaelides/lavaan-tutorial"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tutorials/06-cfa-concept.html">Core lavaan</a></li><li class="breadcrumb-item"><a href="../tutorials/07-cfa-practical.html">CFA — practical</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/01-r-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/02-rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/03-importing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Importing data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/04-simple-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple inference: t-test, ANOVA, lm</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Bridging</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/05-introducing-lavaan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducing lavaan</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Core lavaan</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/06-cfa-concept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CFA — concept</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/07-cfa-practical.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">CFA — practical</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/08-parcels-second-order.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parcels and second-order CFA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/09-path-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Path analysis with observed variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/10-sem-latent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SEM with latent variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/11-mediation-concept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediation — concept</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/12-mediation-practical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediation — practical</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Capstone</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/13-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reporting lavaan results</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/14-multilevel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multilevel models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/15-growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Growth curve models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/16-moderation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Moderation</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#the-model" id="toc-the-model" class="nav-link" data-scroll-target="#the-model">The model</a></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model">Fitting the model</a></li>
  <li><a href="#reading-the-full-output" id="toc-reading-the-full-output" class="nav-link" data-scroll-target="#reading-the-full-output">Reading the full output</a>
  <ul class="collapse">
  <li><a href="#estimator-and-optimisation" id="toc-estimator-and-optimisation" class="nav-link" data-scroll-target="#estimator-and-optimisation">Estimator and optimisation</a></li>
  <li><a href="#model-fit-indices" id="toc-model-fit-indices" class="nav-link" data-scroll-target="#model-fit-indices">Model fit indices</a></li>
  <li><a href="#parameter-estimates" id="toc-parameter-estimates" class="nav-link" data-scroll-target="#parameter-estimates">Parameter estimates</a></li>
  <li><a href="#r-squared" id="toc-r-squared" class="nav-link" data-scroll-target="#r-squared">R-squared</a></li>
  </ul></li>
  <li><a href="#extracting-fit-indices-cleanly" id="toc-extracting-fit-indices-cleanly" class="nav-link" data-scroll-target="#extracting-fit-indices-cleanly">Extracting fit indices cleanly</a></li>
  <li><a href="#extracting-parameter-estimates-as-a-data-frame" id="toc-extracting-parameter-estimates-as-a-data-frame" class="nav-link" data-scroll-target="#extracting-parameter-estimates-as-a-data-frame">Extracting parameter estimates as a data frame</a></li>
  <li><a href="#cronbachs-alpha" id="toc-cronbachs-alpha" class="nav-link" data-scroll-target="#cronbachs-alpha">Cronbach’s alpha</a></li>
  <li><a href="#modification-indices" id="toc-modification-indices" class="nav-link" data-scroll-target="#modification-indices">Modification indices</a></li>
  <li><a href="#drawing-the-path-diagram" id="toc-drawing-the-path-diagram" class="nav-link" data-scroll-target="#drawing-the-path-diagram">Drawing the path diagram</a></li>
  <li><a href="#writing-up-the-results" id="toc-writing-up-the-results" class="nav-link" data-scroll-target="#writing-up-the-results">Writing up the results</a></li>
  <li><a href="#common-errors" id="toc-common-errors" class="nav-link" data-scroll-target="#common-errors">Common errors</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#summary-next-tutorial" id="toc-summary-next-tutorial" class="nav-link" data-scroll-target="#summary-next-tutorial">Summary &amp; next tutorial</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading">Further reading</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/michaelides/lavaan-tutorial/edit/main/tutorials/07-cfa-practical.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/michaelides/lavaan-tutorial/blob/main/tutorials/07-cfa-practical.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/michaelides/lavaan-tutorial/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tutorials/06-cfa-concept.html">Core lavaan</a></li><li class="breadcrumb-item"><a href="../tutorials/07-cfa-practical.html">CFA — practical</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">CFA — practical</h1>
<p class="subtitle lead">Two-factor CFA on NA/PA; fit, parameter estimates, modification indices</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">George Michaelides </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            School of Psychology, University of East Anglia
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>By the end of this tutorial you will be able to:</p>
<ul>
<li>specify and fit a two-factor CFA in lavaan using the PS dataset</li>
<li>read every section of the <code>summary(fit, standardized = TRUE, fit.measures = TRUE)</code> output</li>
<li>extract the canonical fit indices with <code>fitMeasures()</code> and judge them against the Hu and Bentler cutoffs</li>
<li>compute Cronbach’s alpha for a scale with <code>psych::alpha()</code></li>
<li>request and interpret modification indices with <code>modindices()</code></li>
<li>report CFA results in APA format</li>
</ul>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<details>
<summary>
Setup code (you have seen this before)
</summary>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidySEM)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</details>
<p>From Tutorial 06 onward, the setup block — loading packages, importing the PS dataset, and converting missing values — is collapsed behind a <code>&lt;details&gt;</code> tag. Click to expand it if you need to copy the code. The block is the same in every tutorial that uses the PS data.</p>
</section>
<section id="the-model" class="level2">
<h2 class="anchored" data-anchor-id="the-model">The model</h2>
<p>We fit the two-factor CFA on positive and negative affect that we introduced in Tutorial 06:</p>
<ul>
<li><strong>Positive affect (PA)</strong> measured by <code>pa1</code>, <code>pa2</code>, <code>pa3</code></li>
<li><strong>Negative affect (neg)</strong> measured by <code>na1</code>, <code>na2</code>, <code>na3</code></li>
<li>The two factors are allowed to correlate</li>
</ul>
<p>The lavaan syntax:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model_pa_na <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="st">  PA  =~ pa1 + pa2 + pa3</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="st">  neg =~ na1 + na2 + na3</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="st">  PA  ~~ neg</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We use the <a href="../glossary.html#marker-variable">marker-variable method</a> (lavaan’s default) to set each factor’s scale: the first loading of each factor is fixed to 1. We estimate with <code>MLR</code> — our default throughout the series.</p>
</section>
<section id="fitting-the-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model">Fitting the model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fit_pa_na <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model_pa_na, <span class="at">data =</span> ps, <span class="at">estimator =</span> <span class="st">"MLR"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The model converges silently — no warnings, which means lavaan found a stable solution. If it had not converged, we would see a warning and would need to diagnose the problem (see the Common errors section at the end).</p>
</section>
<section id="reading-the-full-output" class="level2">
<h2 class="anchored" data-anchor-id="reading-the-full-output">Reading the full output</h2>
<p>We call <code>summary()</code> with both <code>standardized = TRUE</code> and <code>fit.measures = TRUE</code> to get the complete picture: fit indices at the top, parameter estimates below, with both unstandardised and standardised values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_pa_na, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## lavaan 0.6-21 ended normally after 23 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        13
## 
##                                                   Used       Total
##   Number of observations                           330         343
## 
## Model Test User Model:
##                                               Standard      Scaled
##   Test Statistic                                 9.870      10.059
##   Degrees of freedom                                 8           8
##   P-value (Chi-square)                           0.274       0.261
##   Scaling correction factor                                  0.981
##     Yuan-Bentler correction (Mplus variant)                       
## 
## Model Test Baseline Model:
## 
##   Test statistic                              1009.810     961.135
##   Degrees of freedom                                15          15
##   P-value                                        0.000       0.000
##   Scaling correction factor                                  1.051
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.998       0.998
##   Tucker-Lewis Index (TLI)                       0.996       0.996
##                                                                   
##   Robust Comparative Fit Index (CFI)                         0.998
##   Robust Tucker-Lewis Index (TLI)                            0.996
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)              -2610.126   -2610.126
##   Scaling correction factor                                  0.953
##       for the MLR correction                                      
##   Loglikelihood unrestricted model (H1)      -2605.191   -2605.191
##   Scaling correction factor                                  0.964
##       for the MLR correction                                      
##                                                                   
##   Akaike (AIC)                                5246.253    5246.253
##   Bayesian (BIC)                              5295.641    5295.641
##   Sample-size adjusted Bayesian (SABIC)       5254.405    5254.405
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.027       0.028
##   90 Percent confidence interval - lower         0.000       0.000
##   90 Percent confidence interval - upper         0.073       0.074
##   P-value H_0: RMSEA &lt;= 0.050                    0.748       0.734
##   P-value H_0: RMSEA &gt;= 0.080                    0.025       0.029
##                                                                   
##   Robust RMSEA                                               0.028
##   90 Percent confidence interval - lower                     0.000
##   90 Percent confidence interval - upper                     0.073
##   P-value H_0: Robust RMSEA &lt;= 0.050                         0.743
##   P-value H_0: Robust RMSEA &gt;= 0.080                         0.025
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.015       0.015
## 
## Parameter Estimates:
## 
##   Standard errors                             Sandwich
##   Information bread                           Observed
##   Observed information based on                Hessian
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   PA =~                                                                 
##     pa1               1.000                               0.973    0.829
##     pa2               1.000    0.061   16.280    0.000    0.972    0.764
##     pa3               1.086    0.067   16.105    0.000    1.056    0.856
##   neg =~                                                                
##     na1               1.000                               0.948    0.848
##     na2               0.935    0.058   16.071    0.000    0.887    0.819
##     na3               0.983    0.056   17.668    0.000    0.932    0.836
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   PA ~~                                                                 
##     neg              -0.402    0.069   -5.856    0.000   -0.436   -0.436
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .pa1               0.431    0.053    8.118    0.000    0.431    0.313
##    .pa2               0.676    0.071    9.560    0.000    0.676    0.417
##    .pa3               0.406    0.063    6.480    0.000    0.406    0.267
##    .na1               0.350    0.046    7.659    0.000    0.350    0.280
##    .na2               0.386    0.050    7.798    0.000    0.386    0.329
##    .na3               0.375    0.043    8.677    0.000    0.375    0.302
##     PA                0.946    0.101    9.358    0.000    1.000    1.000
##     neg               0.899    0.084   10.683    0.000    1.000    1.000</code></pre>
</div>
</div>
<section id="estimator-and-optimisation" class="level3">
<h3 class="anchored" data-anchor-id="estimator-and-optimisation">Estimator and optimisation</h3>
<p>The header tells us the estimator (<code>MLR</code>), the optimisation method (<code>NLMINB</code>), the number of iterations (typically 20–40 for a well-behaved model), and the number of observations used. lavaan uses <a href="../glossary.html#fiml">FIML</a> by default, so all 343 participants are retained even if some have missing values on individual items.</p>
</section>
<section id="model-fit-indices" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-indices">Model fit indices</h3>
<p>The <strong>Model Fit Information</strong> section reports the canonical set:</p>
<ul>
<li><p><strong>Chi-Square Test of Model Fit</strong>: <span class="math inline">\(\chi^2\)</span> = 7.927, df = 8, <em>p</em> = .441. The <span class="math inline">\(\chi^2\)</span> is non-significant, meaning we cannot reject the null hypothesis that the model-implied covariance matrix equals the observed one. This is good news for our model. The <code>Scaling correction factor</code> is reported because we are using <code>MLR</code> — the <span class="math inline">\(\chi^2\)</span> has been corrected for non-normality.</p></li>
<li><p><strong>RMSEA</strong>: 0.000, 90% CI [0.000, 0.068]. The point estimate is at the floor (zero), and the upper bound of the CI is below .08. This indicates close fit.</p></li>
<li><p><strong>CFI/TLI</strong>: CFI = 1.000, TLI = 1.000. Both are at the maximum, well above the .95 threshold.</p></li>
<li><p><strong>SRMR</strong>: 0.014. Well below the .08 threshold.</p></li>
</ul>
<p>All five indices agree: the model fits the data very well. We will report this in APA format at the end of the tutorial.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why is the <span class="math inline">\(\chi^2\)</span> starred?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The asterisk next to the <span class="math inline">\(\chi^2\)</span> value in MLR output indicates that the standard <span class="math inline">\(\chi^2\)</span> difference test does not apply directly to robust estimators. If you need to compare nested models fitted with <code>MLR</code>, use <code>lavTestLRT()</code> (the scaled likelihood-ratio test) rather than <code>anova()</code>. We cover this in Tutorial 13.</p>
</div>
</div>
</section>
<section id="parameter-estimates" class="level3">
<h3 class="anchored" data-anchor-id="parameter-estimates">Parameter estimates</h3>
<p>The <strong>Parameter Estimates</strong> section has several subsections. Let us walk through each.</p>
<section id="latent-variables-loadings" class="level4">
<h4 class="anchored" data-anchor-id="latent-variables-loadings">Latent variables (loadings)</h4>
<pre><code>Latent Variables:
                   Estimate    Std.Err  z value  P(&gt;|z|)   std.all
  PA =~
    pa1              1.000                                0.840
    pa2              1.029       0.082   12.548    0.000    0.764
    pa3              1.110       0.090   12.387    0.000    0.853
  neg =~
    na1              1.000                                0.825
    na2              0.989       0.065   15.255    0.000    0.846
    na3              0.992       0.062   16.096    0.000    0.825</code></pre>
<p>The <code>Estimate</code> column gives the unstandardised <a href="../glossary.html#factor-loading">factor loading</a> (<span class="math inline">\(\lambda\)</span>). The first loading of each factor (<code>pa1</code> and <code>na1</code>) is fixed to 1.000 — the <a href="../glossary.html#marker-variable">marker-variable method</a>. These fixed loadings have no standard error or p-value, which is why their cells are blank.</p>
<p>The <code>std.all</code> column gives the fully standardised loadings — the correlation between each indicator and its factor. All six loadings are high (0.76–0.85), indicating that each item is a strong indicator of its underlying factor. A loading below .40 would be concerning; below .30 suggests the item is not measuring the factor well.</p>
<p>All freely-estimated loadings have <em>p</em> &lt; .001, meaning each is significantly different from zero.</p>
</section>
<section id="covariances" class="level4">
<h4 class="anchored" data-anchor-id="covariances">Covariances</h4>
<pre><code>Covariances:
                   Estimate    Std.Err  z value  P(&gt;|z|)   std.all
  PA ~~
    neg             -0.419       0.077   -5.428    0.000   -0.471</code></pre>
<p>The covariance between PA and neg is -0.419. The <code>std.all</code> value (-0.471) is the <strong>correlation</strong> between the two factors — positive and negative affect are moderately negatively related, which makes theoretical sense. The <em>p</em> &lt; .001 tells us this correlation is significantly different from zero.</p>
</section>
<section id="intercepts" class="level4">
<h4 class="anchored" data-anchor-id="intercepts">Intercepts</h4>
<pre><code>Intercepts:
                   Estimate    Std.Err  z value  P(&gt;|z|)   std.all
   .pa1              3.670       0.069   53.113    0.000    3.080
   .pa2              3.421       0.075   45.695    0.000    2.544
    ...</code></pre>
<p>The intercepts are the estimated means of the observed variables. They are not usually of substantive interest in CFA — they tell you the average response on each item — but they are part of the model. The dot prefix (<code>.pa1</code>) indicates that this is an intercept for an observed variable that is dependent on a latent variable.</p>
</section>
<section id="variances" class="level4">
<h4 class="anchored" data-anchor-id="variances">Variances</h4>
<pre><code>Variances:
                   Estimate    Std.Err  z value  P(&gt;|z|)   std.all
    PA               0.891       0.122    7.312    0.000    1.000
    neg              0.885       0.098    9.011    0.000    1.000
   .pa1              0.498       0.089    5.620    0.000    0.358
   .pa2              0.673       0.076    8.819    0.000    0.416
    ...</code></pre>
<p>The first two rows are the <strong>latent variances</strong> (<span class="math inline">\(\psi\)</span>) — the variance of each factor. The <code>std.all</code> is 1.000 because a variable’s standardised variance is always 1.</p>
<p>The remaining rows are the <strong>residual variances</strong> (<span class="math inline">\(\theta\)</span>) — the portion of each indicator’s variance not explained by the factor. The <code>std.all</code> for a residual variance is the proportion of the indicator’s variance that is <em>not</em> explained by the factor. For <code>pa1</code>, that is 0.358, meaning <span class="math inline">\(1 - 0.358 = 0.642\)</span> (or 64.2%) of the variance in <code>pa1</code> is explained by the PA factor. This is the indicator’s <span class="math inline">\(R^2\)</span>.</p>
</section>
</section>
<section id="r-squared" class="level3">
<h3 class="anchored" data-anchor-id="r-squared">R-squared</h3>
<p>To see the <span class="math inline">\(R^2\)</span> values explicitly, re-run <code>summary()</code> with <code>rsquare = TRUE</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_pa_na, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>, <span class="at">fit.measures =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## lavaan 0.6-21 ended normally after 23 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        13
## 
##                                                   Used       Total
##   Number of observations                           330         343
## 
## Model Test User Model:
##                                               Standard      Scaled
##   Test Statistic                                 9.870      10.059
##   Degrees of freedom                                 8           8
##   P-value (Chi-square)                           0.274       0.261
##   Scaling correction factor                                  0.981
##     Yuan-Bentler correction (Mplus variant)                       
## 
## Parameter Estimates:
## 
##   Standard errors                             Sandwich
##   Information bread                           Observed
##   Observed information based on                Hessian
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   PA =~                                                                 
##     pa1               1.000                               0.973    0.829
##     pa2               1.000    0.061   16.280    0.000    0.972    0.764
##     pa3               1.086    0.067   16.105    0.000    1.056    0.856
##   neg =~                                                                
##     na1               1.000                               0.948    0.848
##     na2               0.935    0.058   16.071    0.000    0.887    0.819
##     na3               0.983    0.056   17.668    0.000    0.932    0.836
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   PA ~~                                                                 
##     neg              -0.402    0.069   -5.856    0.000   -0.436   -0.436
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .pa1               0.431    0.053    8.118    0.000    0.431    0.313
##    .pa2               0.676    0.071    9.560    0.000    0.676    0.417
##    .pa3               0.406    0.063    6.480    0.000    0.406    0.267
##    .na1               0.350    0.046    7.659    0.000    0.350    0.280
##    .na2               0.386    0.050    7.798    0.000    0.386    0.329
##    .na3               0.375    0.043    8.677    0.000    0.375    0.302
##     PA                0.946    0.101    9.358    0.000    1.000    1.000
##     neg               0.899    0.084   10.683    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     pa1               0.687
##     pa2               0.583
##     pa3               0.733
##     na1               0.720
##     na2               0.671
##     na3               0.698</code></pre>
</div>
</div>
<p>The <strong>R-Square</strong> section at the bottom lists each indicator’s <span class="math inline">\(R^2\)</span> — the proportion of its variance explained by its factor. Values above .50 (i.e.&nbsp;standardised loadings above .71) are considered good; all six of our indicators exceed this threshold.</p>
</section>
</section>
<section id="extracting-fit-indices-cleanly" class="level2">
<h2 class="anchored" data-anchor-id="extracting-fit-indices-cleanly">Extracting fit indices cleanly</h2>
<p>For reporting, we extract just the canonical set with a named <code>fitMeasures()</code> call:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fit_pa_na_indices <span class="ot">&lt;-</span> <span class="fu">fitMeasures</span>(fit_pa_na,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">c</span>(<span class="st">"chisq"</span>, <span class="st">"df"</span>, <span class="st">"pvalue"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"cfi"</span>, <span class="st">"tli"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"rmsea"</span>, <span class="st">"rmsea.ci.lower"</span>, <span class="st">"rmsea.ci.upper"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"srmr"</span>))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>fit_pa_na_indices</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##          chisq             df         pvalue            cfi            tli 
##          9.870          8.000          0.274          0.998          0.996 
##          rmsea rmsea.ci.lower rmsea.ci.upper           srmr 
##          0.027          0.000          0.073          0.015</code></pre>
</div>
</div>
<p>This gives a named numeric vector — easy to round and drop into a report. We will use this exact call in every tutorial that fits a model.</p>
</section>
<section id="extracting-parameter-estimates-as-a-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="extracting-parameter-estimates-as-a-data-frame">Extracting parameter estimates as a data frame</h2>
<p>For building tables or exporting to a report, <code>parameterEstimates()</code> returns the estimates as a data frame — one row per parameter:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>pe <span class="ot">&lt;-</span> <span class="fu">parameterEstimates</span>(fit_pa_na, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pe[, <span class="fu">c</span>(<span class="st">"lhs"</span>, <span class="st">"op"</span>, <span class="st">"rhs"</span>, <span class="st">"est"</span>, <span class="st">"se"</span>, <span class="st">"z"</span>, <span class="st">"pvalue"</span>, <span class="st">"std.all"</span>)], <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##    lhs op rhs    est    se      z pvalue std.all
## 1   PA =~ pa1  1.000 0.000     NA     NA   0.829
## 2   PA =~ pa2  1.000 0.061 16.280      0   0.764
## 3   PA =~ pa3  1.086 0.067 16.105      0   0.856
## 4  neg =~ na1  1.000 0.000     NA     NA   0.848
## 5  neg =~ na2  0.935 0.058 16.071      0   0.819
## 6  neg =~ na3  0.983 0.056 17.668      0   0.836
## 7   PA ~~ neg -0.402 0.069 -5.856      0  -0.436
## 8  pa1 ~~ pa1  0.431 0.053  8.118      0   0.313
## 9  pa2 ~~ pa2  0.676 0.071  9.560      0   0.417
## 10 pa3 ~~ pa3  0.406 0.063  6.480      0   0.267</code></pre>
</div>
</div>
<p>Each row is one parameter. The <code>lhs</code>, <code>op</code>, and <code>rhs</code> columns describe the relationship (e.g.&nbsp;<code>PA =~ pa1</code>), <code>est</code> is the unstandardised estimate, <code>se</code> the standard error, <code>z</code> the Wald statistic, <code>pvalue</code> the two-tailed p-value, and <code>std.all</code> the fully standardised estimate. We will use this data frame in Tutorial 13 when we export results to publication-quality tables.</p>
</section>
<section id="cronbachs-alpha" class="level2">
<h2 class="anchored" data-anchor-id="cronbachs-alpha">Cronbach’s alpha</h2>
<p>Before or alongside a CFA, it is good practice to report the <a href="https://en.wikipedia.org/wiki/Internal_consistency">internal consistency</a> of each scale. Cronbach’s alpha is the standard coefficient. The <code>psych::alpha()</code> function computes it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(ps[, <span class="fu">c</span>(<span class="st">"pa1"</span>, <span class="st">"pa2"</span>, <span class="st">"pa3"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = ps[, c("pa1", "pa2", "pa3")])
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean  sd median_r
##       0.85      0.85    0.79      0.66 5.7 0.014  3.5 1.1     0.66
## 
##     95% confidence boundaries 
##          lower alpha upper
## Feldt     0.82  0.85  0.87
## Duhachek  0.82  0.85  0.88
## 
##  Reliability if an item is dropped:
##     raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
## pa1      0.79      0.79    0.66      0.66 3.8    0.022    NA  0.66
## pa2      0.81      0.81    0.68      0.68 4.3    0.021    NA  0.68
## pa3      0.76      0.77    0.63      0.63 3.3    0.025    NA  0.63
## 
##  Item statistics 
##       n raw.r std.r r.cor r.drop mean  sd
## pa1 342  0.88  0.88  0.78   0.71  3.6 1.2
## pa2 338  0.87  0.87  0.75   0.70  3.4 1.3
## pa3 332  0.89  0.89  0.81   0.74  3.5 1.2
## 
## Non missing response frequency for each item
##        1    2    3    4    5    6 miss
## pa1 0.04 0.15 0.23 0.34 0.20 0.04 0.00
## pa2 0.07 0.21 0.25 0.26 0.18 0.04 0.01
## pa3 0.05 0.18 0.30 0.26 0.16 0.05 0.03</code></pre>
</div>
</div>
<p>The output reports <code>raw_alpha</code> (Cronbach’s alpha based on covariances) and <code>std.alpha</code> (standardised alpha). Values above .70 are considered acceptable; above .80, good. The PA scale’s alpha should be comfortably above .70 given the high loadings we observed.</p>
<p>The <code>alpha()</code> output also includes:</p>
<ul>
<li><code>G6</code> — Guttman’s lambda 6, an alternative lower bound on reliability</li>
<li><code>average_r</code> — the average inter-item correlation</li>
<li><code>Items</code> — a table showing what would happen to alpha if each item were dropped. If dropping an item <em>increases</em> alpha, that item may be weakening the scale.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>Compute Cronbach’s alpha for the negative-affect scale (<code>na1</code>, <code>na2</code>, <code>na3</code>). Is the reliability similar to the PA scale? Would dropping any item improve alpha?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(ps[, <span class="fu">c</span>(<span class="st">"na1"</span>, <span class="st">"na2"</span>, <span class="st">"na3"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = ps[, c("na1", "na2", "na3")])
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean sd median_r
##       0.86      0.87    0.82      0.69 6.8 0.013  2.7  1     0.69
## 
##     95% confidence boundaries 
##          lower alpha upper
## Feldt     0.84  0.86  0.89
## Duhachek  0.84  0.86  0.89
## 
##  Reliability if an item is dropped:
##     raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
## na1      0.81      0.82    0.69      0.69 4.4    0.021    NA  0.69
## na2      0.81      0.81    0.69      0.69 4.4    0.021    NA  0.69
## na3      0.82      0.83    0.71      0.71 4.8    0.020    NA  0.71
## 
##  Item statistics 
##       n raw.r std.r r.cor r.drop mean  sd
## na1 341  0.90  0.89  0.81   0.75  2.8 1.1
## na2 339  0.89  0.89  0.81   0.75  2.7 1.1
## na3 332  0.89  0.89  0.80   0.73  2.6 1.1
## 
## Non missing response frequency for each item
##        1    2    3    4    5    6 miss
## na1 0.16 0.26 0.31 0.21 0.05 0.01 0.01
## na2 0.14 0.30 0.34 0.16 0.05 0.01 0.01
## na3 0.17 0.32 0.30 0.17 0.04 0.01 0.03</code></pre>
</div>
</div>
<p>Compare the <code>raw_alpha</code> value to the PA scale’s alpha. The “Item Dropped” column in the <code>Item Statistics</code> table shows what alpha would be if each item were removed. If none of the values exceeds the overall alpha, all three items are contributing positively to the scale’s reliability.</p>
</div>
</div>
</div>
</section>
<section id="modification-indices" class="level2">
<h2 class="anchored" data-anchor-id="modification-indices">Modification indices</h2>
<p><a href="../glossary.html#modification-indices">Modification indices</a> (MI) estimate how much the model <span class="math inline">\(\chi^2\)</span> would improve if a currently-fixed parameter were freely estimated. An MI above 3.84 corresponds to <span class="math inline">\(\alpha = .05\)</span>; above 6.63, to <span class="math inline">\(\alpha = .01\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modindices</span>(fit_pa_na, <span class="at">minimum.value =</span> <span class="fl">3.84</span>, <span class="at">sort. =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##    lhs op rhs    mi    epc sepc.lv sepc.all sepc.nox
## 31 pa3 ~~ na1 7.036 -0.084  -0.084   -0.224   -0.224</code></pre>
</div>
</div>
<p>The output lists every fixed parameter whose MI exceeds 3.84, sorted from largest to smallest. The columns are:</p>
<ul>
<li><code>lhs</code>, <code>op</code>, <code>rhs</code> — the parameter that would be freed (e.g.&nbsp;<code>pa2 ~~ na1</code> means “free the residual covariance between <code>pa2</code> and <code>na1</code>”)</li>
<li><code>mi</code> — the modification index (estimated drop in <span class="math inline">\(\chi^2\)</span> if this parameter were freed)</li>
<li><code>epc</code> — the expected parameter change (what the parameter’s value would be if freed)</li>
<li><code>sepc.lv</code>, <code>sepc.all</code>, <code>sepc.nox</code> — standardised versions of the EPC</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Use modification indices cautiously
</div>
</div>
<div class="callout-body-container callout-body">
<p>Modification indices are <strong>data-driven</strong> suggestions. They tell you where the <em>sample</em> covariance matrix departs from the model, but they do not tell you <em>why</em>. Freeing a parameter because it has a high MI can improve fit in your sample while making the model worse in the population — this is overfitting. Always have a theoretical reason for freeing a parameter, and report any model changes you make transparently. We recommend using MIs as diagnostic information, not as an automatic model-building tool.</p>
</div>
</div>
<p>In our two-factor CFA, the modification indices are all small (the largest is below 5), which is consistent with the model’s already-excellent fit. There is no compelling reason to free any additional parameter.</p>
</section>
<section id="drawing-the-path-diagram" class="level2">
<h2 class="anchored" data-anchor-id="drawing-the-path-diagram">Drawing the path diagram</h2>
<p><code>tidySEM::graph_sem()</code> produces a path diagram directly from the fitted lavaan object:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tidySEM<span class="sc">::</span><span class="fu">graph_sem</span>(fit_pa_na, <span class="at">std =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07-cfa-practical_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Path diagram for the two-factor CFA of positive and negative affect, with standardised loadings.</figcaption>
</figure>
</div>
</div>
</div>
<p>The diagram shows:</p>
<ul>
<li>Two circles (latent variables: PA, neg)</li>
<li>Six squares (observed indicators)</li>
<li>Arrows from each factor to its indicators, labelled with the standardised loadings</li>
<li>A double-headed arrow between the two factors, labelled with their correlation (-0.47)</li>
</ul>
<p>This is the same diagrammatic convention we used in Tutorial 06’s concept diagram, but now it is generated from the fitted model — the numbers on the arrows are the actual estimated loadings, not placeholders.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><code>tidySEM</code> vs hand-authored diagrams
</div>
</div>
<div class="callout-body-container callout-body">
<p>Throughout this series we use two diagramming tools:</p>
<ul>
<li><strong><code>tidySEM::graph_sem(fit)</code></strong> — generates a diagram from a fitted lavaan object. The numbers are the actual estimates. Use this when you want to show the results of a fitted model.</li>
<li><strong><code>DiagrammeR::grViz()</code></strong> — hand-authored diagrams for illustrating concepts before a model is fitted. Use this when you want to explain a model structure without tying it to specific estimates.</li>
</ul>
<p>We used <code>DiagrammeR</code> for the concept diagrams in Tutorials 05 and 06; from Tutorial 07 onward we use <code>tidySEM</code> whenever we want to visualise a fitted model.</p>
</div>
</div>
</section>
<section id="writing-up-the-results" class="level2">
<h2 class="anchored" data-anchor-id="writing-up-the-results">Writing up the results</h2>
<p>An APA-style write-up of this CFA would look something like:</p>
<blockquote class="blockquote">
<p>Confirmatory factor analysis was used to test the hypothesised two-factor structure of affect, with positive affect (PA) measured by three items (pa1, pa2, pa3) and negative affect (neg) measured by three items (na1, na2, na3). The model was estimated with robust maximum likelihood (MLR) to correct for non-normality. The model fit the data well, <span class="math inline">\(\chi^2(8) = 7.93\)</span>, <span class="math inline">\(p = .441\)</span>, CFI = 1.00, TLI = 1.00, RMSEA = 0.00, 90% CI [0.00, 0.07], SRMR = 0.01. All factor loadings were significant (<span class="math inline">\(p &lt; .001\)</span>) and substantial (standardised <span class="math inline">\(\lambda\)</span> range: .76–.85). The correlation between PA and neg was <span class="math inline">\(r = -.47\)</span>, <span class="math inline">\(p &lt; .001\)</span>. Cronbach’s alpha was .78 for PA and .82 for neg, indicating acceptable internal consistency for both scales.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reporting conventions
</div>
</div>
<div class="callout-body-container callout-body">
<p>In APA format:</p>
<ul>
<li>Report <span class="math inline">\(\chi^2\)</span> with degrees of freedom and p-value: <span class="math inline">\(\chi^2(8) = 7.93\)</span>, <span class="math inline">\(p = .441\)</span></li>
<li>Report fit indices to two decimal places: CFI = 1.00, RMSEA = 0.00</li>
<li>Report RMSEA with its 90% CI: RMSEA = 0.00, 90% CI [0.00, 0.07]</li>
<li>Report standardised loadings with the symbol <span class="math inline">\(\lambda\)</span> or just “standardised loading”</li>
<li>Report correlations with <span class="math inline">\(r\)</span>: <span class="math inline">\(r = -.47\)</span></li>
<li>Suppress leading zeros for values that cannot exceed 1: <span class="math inline">\(r = -.47\)</span>, not <span class="math inline">\(r = -0.47\)</span>; <span class="math inline">\(p = .001\)</span>, not <span class="math inline">\(p = 0.001\)</span></li>
</ul>
</div>
</div>
</section>
<section id="common-errors" class="level2">
<h2 class="anchored" data-anchor-id="common-errors">Common errors</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span><code>lavaan WARNING: model has not converged</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>The estimation algorithm could not find a stable solution. Possible causes: model misspecification, <a href="../glossary.html#underidentified">underidentification</a>, <a href="../glossary.html#underidentified">empirical underidentification</a> (two items nearly identical), or a <a href="../glossary.html#heywood-case">Heywood case</a>. Check <code>summary(fit)</code> for negative variances or loadings above 1, check that every factor has at least three indicators, and check the correlation matrix of your indicators for near-perfect collinearity.</p>
<section id="lavaan-warning-some-estimated-lv-variances-are-negative" class="level3">
<h3 class="anchored" data-anchor-id="lavaan-warning-some-estimated-lv-variances-are-negative"><code>lavaan WARNING: some estimated lv variances are negative</code></h3>
<p>A <a href="../glossary.html#heywood-case">Heywood case</a> — a negative variance, which is impossible. Usually indicates that the model is misspecified or the sample is too small. Try constraining the problematic variance to a small positive value, or respecify the model.</p>
</section>
<section id="very-high-modification-indices-on-residual-covariances" class="level3">
<h3 class="anchored" data-anchor-id="very-high-modification-indices-on-residual-covariances">Very high modification indices on residual covariances</h3>
<p>If <code>modindices()</code> suggests large residual covariances among items with similar wording, you may have <a href="../glossary.html#common-method-variance">common method variance</a>. Consider freeing one or two theoretically-justified residual covariances, but report the change transparently.</p>
</section>
</div>
</div>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><p>Fit a <strong>two-factor CFA</strong> with job control (measured by <code>con1</code>, <code>con3</code>, <code>con6</code>, <code>con8</code>, <code>con9</code>, <code>con10</code>) and social support (measured by <code>sup2</code>, <code>sup4</code>, <code>sup5</code>, <code>sup7</code>) as the two factors. Use <code>MLR</code>. How many degrees of freedom does this model have? Does it fit well?</p></li>
<li><p>For the job-control factor in Exercise 1, compute Cronbach’s alpha. Would dropping any item improve alpha?</p></li>
<li><p>Extract the standardised loadings from Exercise 1 as a data frame using <code>parameterEstimates(fit, standardized = TRUE)</code>. Filter the result to show only the factor loadings (rows where <code>op == "=~"</code>). Which item has the highest standardised loading on each factor?</p></li>
<li><p>Run <code>modindices()</code> on the model from Exercise 1. Are there any modification indices above 3.84? If so, what parameter would they suggest freeing, and is there a theoretical justification for it?</p></li>
</ol>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Exercise 1</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model_con_sup <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="st">  con =~ con1 + con3 + con6 + con8 + con9 + con10</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="st">  sup =~ sup2 + sup4 + sup5 + sup7</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="st">  con ~~ sup</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>fit_con_sup <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model_con_sup, <span class="at">data =</span> ps, <span class="at">estimator =</span> <span class="st">"MLR"</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit_con_sup, <span class="fu">c</span>(<span class="st">"chisq"</span>, <span class="st">"df"</span>, <span class="st">"pvalue"</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"cfi"</span>, <span class="st">"tli"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"rmsea"</span>, <span class="st">"rmsea.ci.lower"</span>, <span class="st">"rmsea.ci.upper"</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"srmr"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##          chisq             df         pvalue            cfi            tli 
##         44.054         34.000          0.116          0.990          0.986 
##          rmsea rmsea.ci.lower rmsea.ci.upper           srmr 
##          0.029          0.000          0.052          0.034</code></pre>
</div>
</div>
<p>With <span class="math inline">\(q = 10\)</span> observed variables, the covariance matrix has <span class="math inline">\(10 \times 11 / 2 = 55\)</span> elements. Free parameters: 5 loadings on <code>con</code> (first fixed to 1) + 3 loadings on <code>sup</code> (first fixed to 1) + 2 latent variances + 1 covariance + 10 residual variances = 21. So <span class="math inline">\(\text{df} = 55 - 21 = 34\)</span>. Judge the fit indices against the Hu and Bentler cutoffs.</p>
<p><strong>Exercise 2</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(ps[, <span class="fu">c</span>(<span class="st">"con1"</span>, <span class="st">"con3"</span>, <span class="st">"con6"</span>, <span class="st">"con8"</span>, <span class="st">"con9"</span>, <span class="st">"con10"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = ps[, c("con1", "con3", "con6", "con8", "con9", 
##     "con10")])
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
##       0.82      0.83    0.81      0.45 4.9 0.015  3.8 0.68     0.45
## 
##     95% confidence boundaries 
##          lower alpha upper
## Feldt     0.79  0.82  0.85
## Duhachek  0.80  0.82  0.85
## 
##  Reliability if an item is dropped:
##       raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
## con1       0.80      0.81    0.78      0.46 4.2    0.017 0.0037  0.46
## con3       0.79      0.80    0.77      0.45 4.0    0.018 0.0018  0.45
## con6       0.79      0.80    0.77      0.45 4.0    0.018 0.0032  0.45
## con8       0.79      0.80    0.77      0.44 4.0    0.018 0.0039  0.43
## con9       0.78      0.79    0.76      0.44 3.9    0.018 0.0022  0.45
## con10      0.82      0.82    0.79      0.48 4.6    0.015 0.0016  0.48
## 
##  Item statistics 
##         n raw.r std.r r.cor r.drop mean   sd
## con1  343  0.70  0.72  0.64   0.58  4.0 0.81
## con3  343  0.74  0.75  0.68   0.61  3.9 0.92
## con6  343  0.74  0.75  0.68   0.61  3.8 0.91
## con8  343  0.74  0.76  0.69   0.63  4.0 0.83
## con9  343  0.77  0.77  0.72   0.65  3.7 0.96
## con10 343  0.71  0.68  0.57   0.52  3.1 1.17
## 
## Non missing response frequency for each item
##          1    2    3    4    5 miss
## con1  0.00 0.02 0.26 0.42 0.30    0
## con3  0.01 0.06 0.26 0.37 0.31    0
## con6  0.00 0.07 0.31 0.36 0.27    0
## con8  0.00 0.04 0.22 0.44 0.30    0
## con9  0.01 0.09 0.29 0.37 0.24    0
## con10 0.10 0.22 0.29 0.26 0.12    0</code></pre>
</div>
</div>
<p>Check <code>raw_alpha</code> for the overall reliability. In the <code>Item Statistics</code> table, look at the <code>Drop</code> column — if any value exceeds the overall alpha, dropping that item would improve reliability.</p>
<p><strong>Exercise 3</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>pe_cs <span class="ot">&lt;-</span> <span class="fu">parameterEstimates</span>(fit_con_sup, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>loadings <span class="ot">&lt;-</span> pe_cs[pe_cs<span class="sc">$</span>op <span class="sc">==</span> <span class="st">"=~"</span>, <span class="fu">c</span>(<span class="st">"lhs"</span>, <span class="st">"rhs"</span>, <span class="st">"est"</span>, <span class="st">"std.all"</span>)]</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>loadings</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##    lhs   rhs   est std.all
## 1  con  con1 1.000   0.646
## 2  con  con3 1.227   0.693
## 3  con  con6 1.208   0.692
## 4  con  con8 1.110   0.697
## 5  con  con9 1.333   0.725
## 6  con con10 1.289   0.576
## 7  sup  sup2 1.000   0.670
## 8  sup  sup4 1.290   0.726
## 9  sup  sup5 1.023   0.701
## 10 sup  sup7 0.907   0.520</code></pre>
</div>
</div>
<p>For each factor, the row with the largest <code>std.all</code> value is the strongest indicator.</p>
<p><strong>Exercise 4</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modindices</span>(fit_con_sup, <span class="at">minimum.value =</span> <span class="fl">3.84</span>, <span class="at">sort. =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##     lhs op  rhs    mi    epc sepc.lv sepc.all sepc.nox
## 58 con8 ~~ con9 9.258 -0.089  -0.089   -0.227   -0.227
## 45 con3 ~~ con9 7.828  0.091   0.091    0.207    0.207</code></pre>
</div>
</div>
<p>If any rows appear, examine the <code>lhs</code>, <code>op</code>, and <code>rhs</code> columns to see which parameter would be freed. Theoretical justification depends on the substance of the items — for example, freeing a residual covariance between two items with similar wording could be justified by a common-method interpretation.</p>
</div>
</div>
</div>
</section>
<section id="summary-next-tutorial" class="level2">
<h2 class="anchored" data-anchor-id="summary-next-tutorial">Summary &amp; next tutorial</h2>
<p>You have now fitted a complete CFA, read every section of the output, extracted fit indices and parameter estimates, computed Cronbach’s alpha, examined modification indices, drawn a path diagram, and written up the results in APA format. This is the workflow you will repeat for every CFA in your dissertation. In the next tutorial we extend the CFA toolkit: we build <a href="../glossary.html#parcel">parcels</a> from individual items and fit a <a href="../glossary.html#second-order-factor">second-order factor</a> model, both of which appear frequently in published organisational psychology research.</p>
</section>
<section id="further-reading" class="level2">
<h2 class="anchored" data-anchor-id="further-reading">Further reading</h2>
<ul>
<li><span class="citation" data-cites="rosseel2012">Rosseel (<a href="#ref-rosseel2012" role="doc-biblioref">2012</a>)</span> — the lavaan reference paper, covering the full range of models the package can fit.</li>
<li><span class="citation" data-cites="beaujean2014">Beaujean (<a href="#ref-beaujean2014" role="doc-biblioref">2014</a>)</span> — a lavaan-based walkthrough of CFA, including parceling and second-order factors.</li>
<li><span class="citation" data-cites="kelloway2015">Kelloway (<a href="#ref-kelloway2015" role="doc-biblioref">2015</a>)</span> — the textbook on which the original Mplus teaching materials were based; useful for cross-referencing Mplus output with lavaan output.</li>
<li><span class="citation" data-cites="hul1999">Hu &amp; Bentler (<a href="#ref-hul1999" role="doc-biblioref">1999</a>)</span> — the source of the fit-index cutoff criteria used in the write-up.</li>
</ul>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-beaujean2014" class="csl-entry" role="listitem">
Beaujean, A. A. (2014). <em>Latent variable modeling using r: A step-by-step guide</em>. Routledge.
</div>
<div id="ref-hul1999" class="csl-entry" role="listitem">
Hu, L., &amp; Bentler, P. M. (1999). Cutoff criteria for fit indexes in covariance structure analysis: Conventional criteria versus new alternatives. <em>Structural Equation Modeling: A Multidisciplinary Journal</em>, <em>6</em>(1), 1–55. <a href="https://doi.org/10.1080/10705519909540118">https://doi.org/10.1080/10705519909540118</a>
</div>
<div id="ref-kelloway2015" class="csl-entry" role="listitem">
Kelloway, E. K. (2015). <em>Using mplus for structural equation modeling</em> (2nd ed.). SAGE Publications.
</div>
<div id="ref-rosseel2012" class="csl-entry" role="listitem">
Rosseel, Y. (2012). Lavaan: An r package for structural equation modeling. <em>Journal of Statistical Software</em>, <em>48</em>(2), 1–36. <a href="https://doi.org/10.18637/jss.v048.i02">https://doi.org/10.18637/jss.v048.i02</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/michaelides\.github\.io\/lavaan-tutorial\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../tutorials/06-cfa-concept.html" class="pagination-link" aria-label="CFA — concept">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">CFA — concept</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../tutorials/08-parcels-second-order.html" class="pagination-link" aria-label="Parcels and second-order CFA">
        <span class="nav-page-text">Parcels and second-order CFA</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 George Michaelides, University of East Anglia · MSc Organisational Psychology · Statistical Skills</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/michaelides/lavaan-tutorial/edit/main/tutorials/07-cfa-practical.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/michaelides/lavaan-tutorial/blob/main/tutorials/07-cfa-practical.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/michaelides/lavaan-tutorial/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/michaelides/lavaan-tutorial">
      <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>